export const FETCH_TODOS_STARTED = "FETCH_TODOS_STARTED";
export const FETCH_TODOS_SUCCEEDED = "RECEIVE_HELLO_WORLD";
export const FETCH_TODOS_FAILED = "FETCH_TODOS_FAILED";

export const INIT_UPDATE_TODO = "INIT_UPDATE_TODO";

export const FETCH_ADD_TODO_STARTED = "FETCH_ADD_TODO_STARTED";
export const FETCH_ADD_TODO_SUCCEEDED = "FETCH_ADD_TODO_SUCCEEDED";
export const FETCH_ADD_TODO_FAILED = "FETCH_ADD_TODO_FAILED";

export const FETCH_UPDATE_TODO_STARTED = "FETCH_UPDATE_TODO_STARTED";
export const FETCH_UPDATE_TODO_SUCCEEDED = "FETCH_UPDATE_TODO_SUCCEEDED";
export const FETCH_UPDATE_TODO_FAILED = "FETCH_UPDATE_TODO_FAILED";

export const FETCH_DELETE_TODO_STARTED = "FETCH_DELETE_TODO_STARTED";
export const FETCH_DELETE_TODO_SUCCEEDED = "FETCH_DELETE_TODO_SUCCEEDED";
export const FETCH_DELETE_TODO_FAILED = "FETCH_DELETE_TODO_FAILED";

export const FETCH_COMPLETE_TODO_STARTED = "FETCH_COMPLETE_TODO_STARTED";
export const FETCH_COMPLETE_TODO_SUCCEEDED = "FETCH_COMPLETE_TODO_SUCCEEDED";
export const FETCH_COMPLETE_TODO_FAILED = "FETCH_COMPLETE_TODO_FAILED";